/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'audio' : IDL.Opt(ExternalBlob),
  'video' : IDL.Opt(ExternalBlob),
  'file' : IDL.Opt(ExternalBlob),
  'recipient' : IDL.Opt(IDL.Principal),
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'image' : IDL.Opt(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const MessageInput = IDL.Record({
  'content' : IDL.Text,
  'audio' : IDL.Opt(ExternalBlob),
  'video' : IDL.Opt(ExternalBlob),
  'file' : IDL.Opt(ExternalBlob),
  'image' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContact' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authenticateAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'authenticateGuest' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteMessageFile' : IDL.Func([IDL.Nat], [], []),
  'editMessageFile' : IDL.Func([IDL.Nat, IDL.Opt(ExternalBlob)], [], []),
  'getAllMessagesForCaller' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getPrivateMessages' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getPublicMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Opt(IDL.Principal)], [IDL.Nat], []),
  'sendMessageWithMedia' : IDL.Func(
      [MessageInput, IDL.Opt(IDL.Principal)],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'audio' : IDL.Opt(ExternalBlob),
    'video' : IDL.Opt(ExternalBlob),
    'file' : IDL.Opt(ExternalBlob),
    'recipient' : IDL.Opt(IDL.Principal),
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'image' : IDL.Opt(ExternalBlob),
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const MessageInput = IDL.Record({
    'content' : IDL.Text,
    'audio' : IDL.Opt(ExternalBlob),
    'video' : IDL.Opt(ExternalBlob),
    'file' : IDL.Opt(ExternalBlob),
    'image' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContact' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authenticateAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'authenticateGuest' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteMessageFile' : IDL.Func([IDL.Nat], [], []),
    'editMessageFile' : IDL.Func([IDL.Nat, IDL.Opt(ExternalBlob)], [], []),
    'getAllMessagesForCaller' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getPrivateMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getPublicMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Opt(IDL.Principal)], [IDL.Nat], []),
    'sendMessageWithMedia' : IDL.Func(
        [MessageInput, IDL.Opt(IDL.Principal)],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };